name: Publish package on NPM

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18.x
          registry-url: https://npm.pkg.github.com/
      - id: createNpmrc
        name: Create .npmrc
        shell: bash
        run: |
          echo "registry=https://registry.npmjs.org/" > .npmrc
          echo "@mayntri:registry=https://npm.pkg.github.com" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> .npmrc
      - run: npm ci
      - run: npm run build
      - run: npm publish --access=private
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}